#!/usr/bin/env python3

import os
import sys

from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("DEEP_TOKEN"), base_url="https://api.deepseek.com"
)

response = client.chat.completions.create(
    model="deepseek-reasoner",
    messages=[
        {"role": "system", "content": "You are a helpful assistant"},
        {"role": "user", "content": sys.argv[1]},
    ],
    stream=True,
)

print("<think>")
for content in response:
    reasoning = content.choices[0].delta.reasoning_content
    if reasoning is None:
        break

    print(reasoning, end="", flush=True)

print("\n</think>\n")

for content in response:
    print(content.choices[0].delta.content, end="", flush=True)

print()
