#!/usr/bin/env python3

import os
import sys

from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("DEEP_TOKEN"), base_url="https://api.deepseek.com"
)

response = client.chat.completions.create(
    model="deepseek-chat",
    messages=[
        {"role": "system", "content": "You are a helpful assistant"},
        {"role": "user", "content": sys.argv[1]},
    ],
    stream=True,
)

# print(response.choices[0].message.content)
for content in response:
    print(content.choices[0].delta.content, end="", flush=True)

print()
