#!/bin/bash

fzf-previwer() {
    fzf --preview-window=up:60% \
        --preview="bat -n --theme=gruvbox-dark --color=always --paging=never {}"
}

fd -L -H -t f -E .git . $@ | fzf-previwer | xargs -r $EDITOR
