#!/usr/bin/env sh

fzf_previwer() {
    fzf --preview-window=up:60% \
        --preview="bat -n --theme=gruvbox-dark --color=always --paging=never {}"
}

fd -L -H -t f -E .git . $@ | fzf_previwer | xargs -r $EDITOR
