#!/usr/bin/env python

import argparse
import sys

from sympy import Function, rsolve, simplify, sympify, latex
from sympy.abc import n

def main() -> int:
    parser = argparse.ArgumentParser(
        description="A script to solve recurrence relationships"
    )

    parser.add_argument(
        "-r",
        "--recurrence",
        type=str,
        required=True,
        help="The recurrence relation to solve",
    )


    parser.add_argument(
        "-i",
        "--initials",
        nargs="+",
        type=int,
        default=None,
        required=False,
        help="The recurrence relation's initial values",
    )

    parser.add_argument(
        "-l",
        "--latex",
        action="store_true",
        required=False,
        default=False,
        help="Print as a LaTex expression",
    )

    args = parser.parse_args()

    a = Function("a")
    
    recurrence = sympify(args.recurrence)
    if args.initials is None:
        print(rsolve(recurrence, a(n)))
        return 0

    initials = {}
    for i in range(0, len(args.initials), 2):
        initials[a(args.initials[i])] = args.initials[i + 1]

    solution = rsolve(recurrence, a(n), initials)

    if args.latex:
        print(latex(solution))
    else:
        print(solution)

    return 0

if __name__ == "__main__":
    sys.exit(main())
