#!/usr/bin/env zsh

max_val=$(($1 ** 0.5))

for ((i = 2; i < max_val; i++)); do
    if [ $(($1 % i)) -eq 0 ]; then
        echo "Factors: ($i, $(($1 / $i)))"
        return 1
    fi
done

echo "Prime"
return 0
