#!/usr/bin/env sh

selected_layout_number=$(grep selected-layout $1 | cut -d: -f2)
next_layout_number=$(((selected_layout + 1) % 2))
next_layout=$(grep $next_layout_number $1 | cut -d: -f1)

layouts=$(sed "s/selected-layout:${selected_layout_number}/selected-layout: ${next_layout_number}/" $1)

# tmux set-hook -g after-split-window "select-layout $next_layout"
# tmxu set-hook -g after-kill-pane "select-layout $next_layout"
# tmux select-layout $next_layout
# selected-layout: 0
# main-vertical: 0
# main-horizontal: 1

echo $layouts
echo $layouts >$1
