#!/usr/bin/env sh

if [ -z "$(pgrep tmux)" ]; then
    tmux start
fi

selected=$(find $1 -type d | sed 's|'"$HOME"/'||' | gum filter)
selected=${selected%/}

# Acount for tmux changing some chars
session_name=$(echo $selected | rev | cut -d'/' --fields=-$2 | rev | tr "." "_")

tmux has-session -t $session_name 2>/dev/null

if [ $? -ne 0 ]; then
    tmux new-session -d -c "$selected" -s "$session_name"
fi
tmux switch-client -t "$session_name"
