#!/usr/bin/env sh

if [ -z "$(pgrep tmux)" ]; then
    tmux start
fi

selected=$(find $1 -type d | sed 's|'"$HOME"/'||' | gum filter)
selected=${selected%/}

tmux new-session -c "$selected" -A -s $(echo $selected | rev | cut -d'/' --fields=-$2 | rev)
