#!/usr/bin/env sh

if [ -z "$(pgrep tmux)" ]; then
    tmux start
fi

selected=$(fd -H -E .git -E node_modules -E venv -t d . $1 | sed 's|'"$HOME"/'||' | gum filter)
selected=${selected%/}

tmux new-session -c "$selected" -A -s $(echo $selected | rev | cut -d'/' --fields=-$2 | rev)
